/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_espace_admin (void)
{
  GtkWidget *espace_admin;
  GtkWidget *fixed1;
  GtkWidget *label4;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *fixed2;
  GtkWidget *treeview_agent;
  GtkWidget *label5;
  GtkWidget *entryfindA;
  GtkWidget *editA;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label8;
  GtkWidget *addA;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label9;
  GtkWidget *findA;
  GtkWidget *image5;
  GtkWidget *deletA;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label6;
  GtkWidget *refershA;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label7;
  GtkWidget *_;
  GtkWidget *fixed3;
  GtkWidget *treeviewHuser;
  GtkWidget *calendar1;
  GtkWidget *entryfindu;
  GtkWidget *label10;
  GtkWidget *findu;
  GtkWidget *image6;
  GtkWidget *arc;
  GtkWidget *label2;
  GtkWidget *fixed6;
  GtkWidget *monitoring;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image10;
  GtkWidget *label44;
  GtkWidget *label3;
  GtkWidget *logout;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label33;

  espace_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_admin), _("Espace-Admin"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (espace_admin), fixed1);

  label4 = gtk_label_new (_("Espace-Administrator "));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 0, 16);
  gtk_widget_set_size_request (label4, 248, 48);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 72);
  gtk_widget_set_size_request (notebook1, 1000, 592);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow1);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed2);

  treeview_agent = gtk_tree_view_new ();
  gtk_widget_show (treeview_agent);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_agent, 16, 48);
  gtk_widget_set_size_request (treeview_agent, 744, 432);

  label5 = gtk_label_new (_("Agent-DataBase"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 16, 8);
  gtk_widget_set_size_request (label5, 168, 32);

  entryfindA = gtk_entry_new ();
  gtk_widget_show (entryfindA);
  gtk_fixed_put (GTK_FIXED (fixed2), entryfindA, 824, 56);
  gtk_widget_set_size_request (entryfindA, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfindA), 8226);

  editA = gtk_button_new ();
  gtk_widget_show (editA);
  gtk_fixed_put (GTK_FIXED (fixed2), editA, 768, 504);
  gtk_widget_set_size_request (editA, 104, 45);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (editA), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Edit"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  addA = gtk_button_new ();
  gtk_widget_show (addA);
  gtk_fixed_put (GTK_FIXED (fixed2), addA, 880, 504);
  gtk_widget_set_size_request (addA, 104, 45);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (addA), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Add"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  findA = gtk_button_new ();
  gtk_widget_show (findA);
  gtk_fixed_put (GTK_FIXED (fixed2), findA, 768, 48);
  gtk_widget_set_size_request (findA, 56, 40);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (findA), image5);

  deletA = gtk_button_new ();
  gtk_widget_show (deletA);
  gtk_fixed_put (GTK_FIXED (fixed2), deletA, 16, 504);
  gtk_widget_set_size_request (deletA, 104, 45);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (deletA), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Delet"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox1), label6, FALSE, FALSE, 0);

  refershA = gtk_button_new ();
  gtk_widget_show (refershA);
  gtk_fixed_put (GTK_FIXED (fixed2), refershA, 136, 504);
  gtk_widget_set_size_request (refershA, 104, 45);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (refershA), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Refresh "));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  _ = gtk_label_new (_("Agent-Mangment "));
  gtk_widget_show (_);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), _);
  gtk_widget_set_size_request (_, 150, -1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  treeviewHuser = gtk_tree_view_new ();
  gtk_widget_show (treeviewHuser);
  gtk_fixed_put (GTK_FIXED (fixed3), treeviewHuser, 16, 48);
  gtk_widget_set_size_request (treeviewHuser, 584, 456);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar1, 680, 40);
  gtk_widget_set_size_request (calendar1, 232, 200);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  entryfindu = gtk_entry_new ();
  gtk_widget_show (entryfindu);
  gtk_fixed_put (GTK_FIXED (fixed3), entryfindu, 752, 275);
  gtk_widget_set_size_request (entryfindu, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfindu), 8226);

  label10 = gtk_label_new (_("History of reserved parking slots "));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 16, 8);
  gtk_widget_set_size_request (label10, 304, 32);

  findu = gtk_button_new ();
  gtk_widget_show (findu);
  gtk_fixed_put (GTK_FIXED (fixed3), findu, 680, 267);
  gtk_widget_set_size_request (findu, 56, 40);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (findu), image6);

  arc = gtk_button_new_with_mnemonic (_("Refrech"));
  gtk_widget_show (arc);
  gtk_fixed_put (GTK_FIXED (fixed3), arc, 248, 512);
  gtk_widget_set_size_request (arc, 104, 45);

  label2 = gtk_label_new (_("User Reservation"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);
  gtk_widget_set_size_request (label2, 150, -1);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  monitoring = gtk_button_new ();
  gtk_widget_show (monitoring);
  gtk_fixed_put (GTK_FIXED (fixed6), monitoring, 408, 216);
  gtk_widget_set_size_request (monitoring, 160, 72);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (monitoring), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image10 = gtk_image_new_from_stock ("gtk-media-record", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox8), image10, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Monitoring"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox8), label44, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("Monitoring"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);
  gtk_widget_set_size_request (label3, 150, -1);

  logout = gtk_button_new ();
  gtk_widget_show (logout);
  gtk_fixed_put (GTK_FIXED (fixed1), logout, 912, 0);
  gtk_widget_set_size_request (logout, 88, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (logout), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Log-out "));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox5), label33, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) editA, "clicked",
                    G_CALLBACK (on_editA_clicked),
                    NULL);
  g_signal_connect ((gpointer) addA, "clicked",
                    G_CALLBACK (on_addA_clicked),
                    NULL);
  g_signal_connect ((gpointer) findA, "clicked",
                    G_CALLBACK (on_findA_clicked),
                    NULL);
  g_signal_connect ((gpointer) deletA, "clicked",
                    G_CALLBACK (on_deletA_clicked),
                    NULL);
  g_signal_connect ((gpointer) refershA, "clicked",
                    G_CALLBACK (on_refershA_clicked),
                    NULL);
  g_signal_connect ((gpointer) calendar1, "day_selected_double_click",
                    G_CALLBACK (on_calendar1_day_selected_double_click),
                    NULL);
  g_signal_connect ((gpointer) findu, "clicked",
                    G_CALLBACK (on_findu_clicked),
                    NULL);
  g_signal_connect ((gpointer) arc, "clicked",
                    G_CALLBACK (on_arc_clicked),
                    NULL);
  g_signal_connect ((gpointer) monitoring, "clicked",
                    G_CALLBACK (on_monitoring_clicked),
                    NULL);
  g_signal_connect ((gpointer) logout, "clicked",
                    G_CALLBACK (on_logout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_admin, espace_admin, "espace_admin");
  GLADE_HOOKUP_OBJECT (espace_admin, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (espace_admin, label4, "label4");
  GLADE_HOOKUP_OBJECT (espace_admin, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (espace_admin, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (espace_admin, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (espace_admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (espace_admin, treeview_agent, "treeview_agent");
  GLADE_HOOKUP_OBJECT (espace_admin, label5, "label5");
  GLADE_HOOKUP_OBJECT (espace_admin, entryfindA, "entryfindA");
  GLADE_HOOKUP_OBJECT (espace_admin, editA, "editA");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (espace_admin, image3, "image3");
  GLADE_HOOKUP_OBJECT (espace_admin, label8, "label8");
  GLADE_HOOKUP_OBJECT (espace_admin, addA, "addA");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (espace_admin, image4, "image4");
  GLADE_HOOKUP_OBJECT (espace_admin, label9, "label9");
  GLADE_HOOKUP_OBJECT (espace_admin, findA, "findA");
  GLADE_HOOKUP_OBJECT (espace_admin, image5, "image5");
  GLADE_HOOKUP_OBJECT (espace_admin, deletA, "deletA");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (espace_admin, image1, "image1");
  GLADE_HOOKUP_OBJECT (espace_admin, label6, "label6");
  GLADE_HOOKUP_OBJECT (espace_admin, refershA, "refershA");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (espace_admin, image2, "image2");
  GLADE_HOOKUP_OBJECT (espace_admin, label7, "label7");
  GLADE_HOOKUP_OBJECT (espace_admin, _, "_");
  GLADE_HOOKUP_OBJECT (espace_admin, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (espace_admin, treeviewHuser, "treeviewHuser");
  GLADE_HOOKUP_OBJECT (espace_admin, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (espace_admin, entryfindu, "entryfindu");
  GLADE_HOOKUP_OBJECT (espace_admin, label10, "label10");
  GLADE_HOOKUP_OBJECT (espace_admin, findu, "findu");
  GLADE_HOOKUP_OBJECT (espace_admin, image6, "image6");
  GLADE_HOOKUP_OBJECT (espace_admin, arc, "arc");
  GLADE_HOOKUP_OBJECT (espace_admin, label2, "label2");
  GLADE_HOOKUP_OBJECT (espace_admin, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (espace_admin, monitoring, "monitoring");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (espace_admin, image10, "image10");
  GLADE_HOOKUP_OBJECT (espace_admin, label44, "label44");
  GLADE_HOOKUP_OBJECT (espace_admin, label3, "label3");
  GLADE_HOOKUP_OBJECT (espace_admin, logout, "logout");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (espace_admin, image7, "image7");
  GLADE_HOOKUP_OBJECT (espace_admin, label33, "label33");

  return espace_admin;
}

GtkWidget*
create_Add_agent (void)
{
  GtkWidget *Add_agent;
  GtkWidget *fixed4;
  GtkWidget *entryname;
  GtkWidget *entrysurname;
  GtkWidget *calendar2;
  GtkObject *spinbuttonyadd_adj;
  GtkWidget *spinbuttonyadd;
  GtkWidget *entryage;
  GtkWidget *label13;
  GtkWidget *label17;
  GtkWidget *label16;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label24;
  GtkWidget *radiobuttonmaleadd;
  GSList *radiobuttonmaleadd_group = NULL;
  GtkWidget *radiobuttonfemaleadd;
  GtkWidget *checkbuttonvadd;
  GtkWidget *checkbuttoncadd;
  GtkWidget *checkbuttonsadd;
  GtkWidget *addag;
  GtkWidget *backadd;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image9;
  GtkWidget *label43;
  GtkWidget *label12;
  GtkWidget *entryid;
  GtkWidget *label11;
  GtkWidget *label45;
  GtkWidget *comboboxentrywladd;
  GtkWidget *checkbuttonfadd;

  Add_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Add_agent), _("Add-agent"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Add_agent), fixed4);

  entryname = gtk_entry_new ();
  gtk_widget_show (entryname);
  gtk_fixed_put (GTK_FIXED (fixed4), entryname, 120, 51);
  gtk_widget_set_size_request (entryname, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryname), 8226);

  entrysurname = gtk_entry_new ();
  gtk_widget_show (entrysurname);
  gtk_fixed_put (GTK_FIXED (fixed4), entrysurname, 120, 88);
  gtk_widget_set_size_request (entrysurname, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrysurname), 8226);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed4), calendar2, 120, 128);
  gtk_widget_set_size_request (calendar2, 190, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbuttonyadd_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonyadd = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonyadd_adj), 1, 0);
  gtk_widget_show (spinbuttonyadd);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonyadd, 120, 464);
  gtk_widget_set_size_request (spinbuttonyadd, 80, 32);

  entryage = gtk_entry_new ();
  gtk_widget_show (entryage);
  gtk_fixed_put (GTK_FIXED (fixed4), entryage, 120, 320);
  gtk_widget_set_size_request (entryage, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryage), 8226);

  label13 = gtk_label_new (_("Age"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 0, 112);
  gtk_widget_set_size_request (label13, 104, 48);

  label17 = gtk_label_new (_("skills"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 0, 520);
  gtk_widget_set_size_request (label17, 104, 48);

  label16 = gtk_label_new (_("Years of\n experience "));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 0, 456);
  gtk_widget_set_size_request (label16, 104, 56);

  label14 = gtk_label_new (_("Gender"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 0, 352);
  gtk_widget_set_size_request (label14, 104, 48);

  label15 = gtk_label_new (_("work location"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 0, 397);
  gtk_widget_set_size_request (label15, 108, 48);

  label24 = gtk_label_new ("");
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 392, 648);
  gtk_widget_set_size_request (label24, 49, 17);

  radiobuttonmaleadd = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (radiobuttonmaleadd);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobuttonmaleadd, 120, 360);
  gtk_widget_set_size_request (radiobuttonmaleadd, 118, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonmaleadd), radiobuttonmaleadd_group);
  radiobuttonmaleadd_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonmaleadd));

  radiobuttonfemaleadd = gtk_radio_button_new_with_mnemonic (NULL, _("Female"));
  gtk_widget_show (radiobuttonfemaleadd);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobuttonfemaleadd, 240, 360);
  gtk_widget_set_size_request (radiobuttonfemaleadd, 118, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfemaleadd), radiobuttonmaleadd_group);
  radiobuttonmaleadd_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfemaleadd));

  checkbuttonvadd = gtk_check_button_new_with_mnemonic (_("vehicle maintenance"));
  gtk_widget_show (checkbuttonvadd);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbuttonvadd, 240, 520);
  gtk_widget_set_size_request (checkbuttonvadd, 176, 24);

  checkbuttoncadd = gtk_check_button_new_with_mnemonic (_("customer service"));
  gtk_widget_show (checkbuttoncadd);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbuttoncadd, 240, 545);
  gtk_widget_set_size_request (checkbuttoncadd, 144, 32);

  checkbuttonsadd = gtk_check_button_new_with_mnemonic (_("security"));
  gtk_widget_show (checkbuttonsadd);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbuttonsadd, 120, 548);
  gtk_widget_set_size_request (checkbuttonsadd, 121, 24);

  addag = gtk_button_new_with_mnemonic (_("Add"));
  gtk_widget_show (addag);
  gtk_fixed_put (GTK_FIXED (fixed4), addag, 168, 624);
  gtk_widget_set_size_request (addag, 72, 39);

  backadd = gtk_button_new ();
  gtk_widget_show (backadd);
  gtk_fixed_put (GTK_FIXED (fixed4), backadd, 0, 624);
  gtk_widget_set_size_request (backadd, 72, 39);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (backadd), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox7), image9, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox7), label43, FALSE, FALSE, 0);

  label12 = gtk_label_new (_("Surname"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 0, 76);
  gtk_widget_set_size_request (label12, 104, 48);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed4), entryid, 120, 16);
  gtk_widget_set_size_request (entryid, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  label11 = gtk_label_new (_("Name"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed4), label11, 0, 40);
  gtk_widget_set_size_request (label11, 104, 48);

  label45 = gtk_label_new (_("ID"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed4), label45, 0, 8);
  gtk_widget_set_size_request (label45, 104, 48);

  comboboxentrywladd = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrywladd);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxentrywladd, 120, 408);
  gtk_widget_set_size_request (comboboxentrywladd, 190, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrywladd), _("North-parking-lot"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrywladd), _("East-parking-lot"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrywladd), _("West-parking-lot"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrywladd), _("Sout-parking-lot"));

  checkbuttonfadd = gtk_check_button_new_with_mnemonic (_("First Aide "));
  gtk_widget_show (checkbuttonfadd);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbuttonfadd, 120, 520);
  gtk_widget_set_size_request (checkbuttonfadd, 121, 24);

  g_signal_connect ((gpointer) calendar2, "day_selected_double_click",
                    G_CALLBACK (on_calendar2_day_selected_double_click),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonmaleadd, "toggled",
                    G_CALLBACK (on_radiobuttonmaleadd_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonfemaleadd, "toggled",
                    G_CALLBACK (on_radiobuttonfemaleadd_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonvadd, "toggled",
                    G_CALLBACK (on_checkbuttonvadd_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttoncadd, "toggled",
                    G_CALLBACK (on_checkbuttoncadd_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonsadd, "toggled",
                    G_CALLBACK (on_checkbuttonsadd_toggled),
                    NULL);
  g_signal_connect ((gpointer) addag, "clicked",
                    G_CALLBACK (on_addag_clicked),
                    NULL);
  g_signal_connect ((gpointer) backadd, "clicked",
                    G_CALLBACK (on_backadd_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonfadd, "toggled",
                    G_CALLBACK (on_checkbuttonfadd_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Add_agent, Add_agent, "Add_agent");
  GLADE_HOOKUP_OBJECT (Add_agent, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Add_agent, entryname, "entryname");
  GLADE_HOOKUP_OBJECT (Add_agent, entrysurname, "entrysurname");
  GLADE_HOOKUP_OBJECT (Add_agent, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (Add_agent, spinbuttonyadd, "spinbuttonyadd");
  GLADE_HOOKUP_OBJECT (Add_agent, entryage, "entryage");
  GLADE_HOOKUP_OBJECT (Add_agent, label13, "label13");
  GLADE_HOOKUP_OBJECT (Add_agent, label17, "label17");
  GLADE_HOOKUP_OBJECT (Add_agent, label16, "label16");
  GLADE_HOOKUP_OBJECT (Add_agent, label14, "label14");
  GLADE_HOOKUP_OBJECT (Add_agent, label15, "label15");
  GLADE_HOOKUP_OBJECT (Add_agent, label24, "label24");
  GLADE_HOOKUP_OBJECT (Add_agent, radiobuttonmaleadd, "radiobuttonmaleadd");
  GLADE_HOOKUP_OBJECT (Add_agent, radiobuttonfemaleadd, "radiobuttonfemaleadd");
  GLADE_HOOKUP_OBJECT (Add_agent, checkbuttonvadd, "checkbuttonvadd");
  GLADE_HOOKUP_OBJECT (Add_agent, checkbuttoncadd, "checkbuttoncadd");
  GLADE_HOOKUP_OBJECT (Add_agent, checkbuttonsadd, "checkbuttonsadd");
  GLADE_HOOKUP_OBJECT (Add_agent, addag, "addag");
  GLADE_HOOKUP_OBJECT (Add_agent, backadd, "backadd");
  GLADE_HOOKUP_OBJECT (Add_agent, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Add_agent, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Add_agent, image9, "image9");
  GLADE_HOOKUP_OBJECT (Add_agent, label43, "label43");
  GLADE_HOOKUP_OBJECT (Add_agent, label12, "label12");
  GLADE_HOOKUP_OBJECT (Add_agent, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (Add_agent, label11, "label11");
  GLADE_HOOKUP_OBJECT (Add_agent, label45, "label45");
  GLADE_HOOKUP_OBJECT (Add_agent, comboboxentrywladd, "comboboxentrywladd");
  GLADE_HOOKUP_OBJECT (Add_agent, checkbuttonfadd, "checkbuttonfadd");

  return Add_agent;
}

GtkWidget*
create_mod_agent (void)
{
  GtkWidget *mod_agent;
  GtkWidget *fixed5;
  GtkWidget *entrynamem;
  GtkWidget *entrysurnamem;
  GtkWidget *calendar3;
  GtkObject *spinbuttonymod_adj;
  GtkWidget *spinbuttonymod;
  GtkWidget *entryagem;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *radiobuttonmalem;
  GSList *radiobuttonmalem_group = NULL;
  GtkWidget *radiobuttonfemalem;
  GtkWidget *checkbuttonfmod;
  GtkWidget *checkbuttonvmod;
  GtkWidget *checkbuttonsmod;
  GtkWidget *checkbuttoncmod;
  GtkWidget *backmod;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label42;
  GtkWidget *modag;
  GtkWidget *label34;
  GtkWidget *label46;
  GtkWidget *entryidm;
  GtkWidget *comboboxentrywlm;

  mod_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mod_agent), _("mod-agent"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (mod_agent), fixed5);

  entrynamem = gtk_entry_new ();
  gtk_widget_show (entrynamem);
  gtk_fixed_put (GTK_FIXED (fixed5), entrynamem, 120, 51);
  gtk_widget_set_size_request (entrynamem, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynamem), 8226);

  entrysurnamem = gtk_entry_new ();
  gtk_widget_show (entrysurnamem);
  gtk_fixed_put (GTK_FIXED (fixed5), entrysurnamem, 120, 88);
  gtk_widget_set_size_request (entrysurnamem, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrysurnamem), 8226);

  calendar3 = gtk_calendar_new ();
  gtk_widget_show (calendar3);
  gtk_fixed_put (GTK_FIXED (fixed5), calendar3, 120, 128);
  gtk_widget_set_size_request (calendar3, 190, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar3),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbuttonymod_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonymod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonymod_adj), 1, 0);
  gtk_widget_show (spinbuttonymod);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbuttonymod, 120, 464);
  gtk_widget_set_size_request (spinbuttonymod, 80, 32);

  entryagem = gtk_entry_new ();
  gtk_widget_show (entryagem);
  gtk_fixed_put (GTK_FIXED (fixed5), entryagem, 120, 320);
  gtk_widget_set_size_request (entryagem, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryagem), 8226);

  label35 = gtk_label_new (_("Surname"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed5), label35, 0, 76);
  gtk_widget_set_size_request (label35, 104, 48);

  label36 = gtk_label_new (_("Age"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed5), label36, 0, 112);
  gtk_widget_set_size_request (label36, 104, 48);

  label37 = gtk_label_new (_("skills"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed5), label37, 0, 520);
  gtk_widget_set_size_request (label37, 104, 48);

  label38 = gtk_label_new (_("Years of\n experience "));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 0, 456);
  gtk_widget_set_size_request (label38, 104, 56);

  label39 = gtk_label_new (_("Gender"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed5), label39, 0, 352);
  gtk_widget_set_size_request (label39, 104, 48);

  label40 = gtk_label_new (_("work location"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed5), label40, 0, 397);
  gtk_widget_set_size_request (label40, 108, 48);

  label41 = gtk_label_new ("");
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed5), label41, 392, 648);
  gtk_widget_set_size_request (label41, 49, 17);

  radiobuttonmalem = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (radiobuttonmalem);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobuttonmalem, 120, 360);
  gtk_widget_set_size_request (radiobuttonmalem, 118, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonmalem), radiobuttonmalem_group);
  radiobuttonmalem_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonmalem));

  radiobuttonfemalem = gtk_radio_button_new_with_mnemonic (NULL, _("Female"));
  gtk_widget_show (radiobuttonfemalem);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobuttonfemalem, 240, 360);
  gtk_widget_set_size_request (radiobuttonfemalem, 118, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfemalem), radiobuttonmalem_group);
  radiobuttonmalem_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfemalem));

  checkbuttonfmod = gtk_check_button_new_with_mnemonic (_("First Aide "));
  gtk_widget_show (checkbuttonfmod);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttonfmod, 120, 520);
  gtk_widget_set_size_request (checkbuttonfmod, 121, 24);

  checkbuttonvmod = gtk_check_button_new_with_mnemonic (_("vehicle maintenance"));
  gtk_widget_show (checkbuttonvmod);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttonvmod, 240, 520);
  gtk_widget_set_size_request (checkbuttonvmod, 176, 24);

  checkbuttonsmod = gtk_check_button_new_with_mnemonic (_("security"));
  gtk_widget_show (checkbuttonsmod);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttonsmod, 120, 548);
  gtk_widget_set_size_request (checkbuttonsmod, 121, 24);

  checkbuttoncmod = gtk_check_button_new_with_mnemonic (_("customer service"));
  gtk_widget_show (checkbuttoncmod);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttoncmod, 240, 545);
  gtk_widget_set_size_request (checkbuttoncmod, 144, 32);

  backmod = gtk_button_new ();
  gtk_widget_show (backmod);
  gtk_fixed_put (GTK_FIXED (fixed5), backmod, 0, 624);
  gtk_widget_set_size_request (backmod, 72, 39);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (backmod), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox6), label42, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label42, 33, 19);

  modag = gtk_button_new_with_mnemonic (_("Modify"));
  gtk_widget_show (modag);
  gtk_fixed_put (GTK_FIXED (fixed5), modag, 184, 624);
  gtk_widget_set_size_request (modag, 72, 39);

  label34 = gtk_label_new (_("Name"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed5), label34, 0, 40);
  gtk_widget_set_size_request (label34, 104, 48);

  label46 = gtk_label_new (_("ID"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed5), label46, 0, 8);
  gtk_widget_set_size_request (label46, 104, 48);

  entryidm = gtk_entry_new ();
  gtk_widget_show (entryidm);
  gtk_fixed_put (GTK_FIXED (fixed5), entryidm, 120, 16);
  gtk_widget_set_size_request (entryidm, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidm), 8226);

  comboboxentrywlm = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrywlm);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxentrywlm, 120, 408);
  gtk_widget_set_size_request (comboboxentrywlm, 190, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrywlm), _("North-parking-lot"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrywlm), _("East-parking-lot"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrywlm), _("West-parking-lot"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrywlm), _("Sout-parking-lot"));

  g_signal_connect ((gpointer) calendar3, "day_selected_double_click",
                    G_CALLBACK (on_calendar3_day_selected_double_click),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonmalem, "toggled",
                    G_CALLBACK (on_radiobuttonmalem_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonfemalem, "toggled",
                    G_CALLBACK (on_radiobuttonfemalem_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonfmod, "toggled",
                    G_CALLBACK (on_checkbuttonfmod_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonvmod, "toggled",
                    G_CALLBACK (on_checkbuttonvmod_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonsmod, "toggled",
                    G_CALLBACK (on_checkbuttonsmod_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttoncmod, "toggled",
                    G_CALLBACK (on_checkbuttoncmod_toggled),
                    NULL);
  g_signal_connect ((gpointer) backmod, "clicked",
                    G_CALLBACK (on_backmod_clicked),
                    NULL);
  g_signal_connect ((gpointer) modag, "clicked",
                    G_CALLBACK (on_modag_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mod_agent, mod_agent, "mod_agent");
  GLADE_HOOKUP_OBJECT (mod_agent, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (mod_agent, entrynamem, "entrynamem");
  GLADE_HOOKUP_OBJECT (mod_agent, entrysurnamem, "entrysurnamem");
  GLADE_HOOKUP_OBJECT (mod_agent, calendar3, "calendar3");
  GLADE_HOOKUP_OBJECT (mod_agent, spinbuttonymod, "spinbuttonymod");
  GLADE_HOOKUP_OBJECT (mod_agent, entryagem, "entryagem");
  GLADE_HOOKUP_OBJECT (mod_agent, label35, "label35");
  GLADE_HOOKUP_OBJECT (mod_agent, label36, "label36");
  GLADE_HOOKUP_OBJECT (mod_agent, label37, "label37");
  GLADE_HOOKUP_OBJECT (mod_agent, label38, "label38");
  GLADE_HOOKUP_OBJECT (mod_agent, label39, "label39");
  GLADE_HOOKUP_OBJECT (mod_agent, label40, "label40");
  GLADE_HOOKUP_OBJECT (mod_agent, label41, "label41");
  GLADE_HOOKUP_OBJECT (mod_agent, radiobuttonmalem, "radiobuttonmalem");
  GLADE_HOOKUP_OBJECT (mod_agent, radiobuttonfemalem, "radiobuttonfemalem");
  GLADE_HOOKUP_OBJECT (mod_agent, checkbuttonfmod, "checkbuttonfmod");
  GLADE_HOOKUP_OBJECT (mod_agent, checkbuttonvmod, "checkbuttonvmod");
  GLADE_HOOKUP_OBJECT (mod_agent, checkbuttonsmod, "checkbuttonsmod");
  GLADE_HOOKUP_OBJECT (mod_agent, checkbuttoncmod, "checkbuttoncmod");
  GLADE_HOOKUP_OBJECT (mod_agent, backmod, "backmod");
  GLADE_HOOKUP_OBJECT (mod_agent, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (mod_agent, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (mod_agent, image8, "image8");
  GLADE_HOOKUP_OBJECT (mod_agent, label42, "label42");
  GLADE_HOOKUP_OBJECT (mod_agent, modag, "modag");
  GLADE_HOOKUP_OBJECT (mod_agent, label34, "label34");
  GLADE_HOOKUP_OBJECT (mod_agent, label46, "label46");
  GLADE_HOOKUP_OBJECT (mod_agent, entryidm, "entryidm");
  GLADE_HOOKUP_OBJECT (mod_agent, comboboxentrywlm, "comboboxentrywlm");

  return mod_agent;
}

GtkWidget*
create_client (void)
{
  GtkWidget *client;
  GtkWidget *fixed7;
  GtkWidget *lougoutclient;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image11;
  GtkWidget *label59;
  GtkWidget *ecid;
  GtkWidget *ecuser;
  GtkWidget *label50;
  GtkWidget *label65;
  GtkWidget *label64;
  GtkWidget *notebook2;
  GtkWidget *fixed8;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *calendarclient;
  GtkWidget *entrydateclient;
  GtkWidget *label55;
  GtkObject *spinbuttonduration_adj;
  GtkWidget *spinbuttonduration;
  GtkWidget *_2;
  GtkWidget *_3;
  GtkWidget *_4;
  GtkWidget *_5;
  GtkWidget *_6;
  GtkWidget *_7;
  GtkWidget *_8;
  GtkWidget *_9;
  GtkWidget *_10;
  GtkWidget *_11;
  GtkWidget *_12;
  GtkWidget *_13;
  GtkWidget *_14;
  GtkWidget *_15;
  GtkWidget *_16;
  GtkWidget *_17;
  GtkWidget *_18;
  GtkWidget *_19;
  GtkWidget *_20;
  GtkWidget *_21;
  GtkWidget *_22;
  GtkWidget *_23;
  GtkWidget *label56;
  GtkWidget *book;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image12;
  GtkWidget *label66;
  GtkWidget *comboboxentry1;
  GtkWidget *_1;
  GtkWidget *_24;
  GtkWidget *label47;
  GtkWidget *fixed9;
  GtkWidget *treeview1;
  GtkWidget *button2;
  GtkWidget *label57;
  GtkWidget *buttonrefrc;
  GtkWidget *buttoncr;
  GtkWidget *label48;
  GtkWidget *fixed10;
  GtkWidget *label58;
  GtkWidget *label49;

  client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (client), _("client"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (client), fixed7);
  gtk_widget_set_size_request (fixed7, -1, 664);

  lougoutclient = gtk_button_new ();
  gtk_widget_show (lougoutclient);
  gtk_fixed_put (GTK_FIXED (fixed7), lougoutclient, 912, 0);
  gtk_widget_set_size_request (lougoutclient, 88, 48);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (lougoutclient), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image11 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox9), image11, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Log-out"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox9), label59, FALSE, FALSE, 0);

  ecid = gtk_entry_new ();
  gtk_widget_show (ecid);
  gtk_fixed_put (GTK_FIXED (fixed7), ecid, 328, 23);
  gtk_widget_set_size_request (ecid, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ecid), 8226);

  ecuser = gtk_entry_new ();
  gtk_widget_show (ecuser);
  gtk_fixed_put (GTK_FIXED (fixed7), ecuser, 632, 23);
  gtk_widget_set_size_request (ecuser, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ecuser), 8226);

  label50 = gtk_label_new (_("Espace Client "));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed7), label50, 24, 16);
  gtk_widget_set_size_request (label50, 232, 40);

  label65 = gtk_label_new (_("USERNAME"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed7), label65, 517, 16);
  gtk_widget_set_size_request (label65, 116, 40);

  label64 = gtk_label_new (_("ID"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed7), label64, 269, 16);
  gtk_widget_set_size_request (label64, 49, 40);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed7), notebook2, 0, 72);
  gtk_widget_set_size_request (notebook2, 1000, 592);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed8);

  label51 = gtk_label_new (_("Parking Area"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed8), label51, 16, 24);
  gtk_widget_set_size_request (label51, 120, 32);

  label52 = gtk_label_new (_("A"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed8), label52, 56, 96);
  gtk_widget_set_size_request (label52, 49, 17);

  label53 = gtk_label_new (_("B"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed8), label53, 320, 96);
  gtk_widget_set_size_request (label53, 49, 17);

  label54 = gtk_label_new (_("C"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed8), label54, 568, 96);
  gtk_widget_set_size_request (label54, 49, 17);

  calendarclient = gtk_calendar_new ();
  gtk_widget_show (calendarclient);
  gtk_fixed_put (GTK_FIXED (fixed8), calendarclient, 160, 264);
  gtk_widget_set_size_request (calendarclient, 190, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendarclient),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  entrydateclient = gtk_entry_new ();
  gtk_widget_show (entrydateclient);
  gtk_fixed_put (GTK_FIXED (fixed8), entrydateclient, 160, 464);
  gtk_widget_set_size_request (entrydateclient, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrydateclient), 8226);

  label55 = gtk_label_new (_("Date"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed8), label55, 48, 288);
  gtk_widget_set_size_request (label55, 49, 17);

  spinbuttonduration_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonduration = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonduration_adj), 1, 0);
  gtk_widget_show (spinbuttonduration);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbuttonduration, 632, 336);
  gtk_widget_set_size_request (spinbuttonduration, 190, 27);

  _2 = gtk_check_button_new_with_mnemonic (_("2"));
  gtk_widget_show (_2);
  gtk_fixed_put (GTK_FIXED (fixed8), _2, 224, 96);
  gtk_widget_set_size_request (_2, 40, 24);

  _3 = gtk_check_button_new_with_mnemonic (_("3"));
  gtk_widget_show (_3);
  gtk_fixed_put (GTK_FIXED (fixed8), _3, 152, 128);
  gtk_widget_set_size_request (_3, 40, 24);

  _4 = gtk_check_button_new_with_mnemonic (_("4"));
  gtk_widget_show (_4);
  gtk_fixed_put (GTK_FIXED (fixed8), _4, 224, 128);
  gtk_widget_set_size_request (_4, 40, 24);

  _5 = gtk_check_button_new_with_mnemonic (_("5"));
  gtk_widget_show (_5);
  gtk_fixed_put (GTK_FIXED (fixed8), _5, 152, 160);
  gtk_widget_set_size_request (_5, 40, 24);

  _6 = gtk_check_button_new_with_mnemonic (_("6"));
  gtk_widget_show (_6);
  gtk_fixed_put (GTK_FIXED (fixed8), _6, 224, 160);
  gtk_widget_set_size_request (_6, 40, 24);

  _7 = gtk_check_button_new_with_mnemonic (_("7"));
  gtk_widget_show (_7);
  gtk_fixed_put (GTK_FIXED (fixed8), _7, 152, 192);
  gtk_widget_set_size_request (_7, 40, 24);

  _8 = gtk_check_button_new_with_mnemonic (_("8"));
  gtk_widget_show (_8);
  gtk_fixed_put (GTK_FIXED (fixed8), _8, 224, 192);
  gtk_widget_set_size_request (_8, 40, 24);

  _9 = gtk_check_button_new_with_mnemonic (_("1"));
  gtk_widget_show (_9);
  gtk_fixed_put (GTK_FIXED (fixed8), _9, 408, 96);
  gtk_widget_set_size_request (_9, 40, 24);

  _10 = gtk_check_button_new_with_mnemonic (_("2"));
  gtk_widget_show (_10);
  gtk_fixed_put (GTK_FIXED (fixed8), _10, 480, 96);
  gtk_widget_set_size_request (_10, 40, 24);

  _11 = gtk_check_button_new_with_mnemonic (_("3"));
  gtk_widget_show (_11);
  gtk_fixed_put (GTK_FIXED (fixed8), _11, 408, 128);
  gtk_widget_set_size_request (_11, 40, 32);

  _12 = gtk_check_button_new_with_mnemonic (_("4"));
  gtk_widget_show (_12);
  gtk_fixed_put (GTK_FIXED (fixed8), _12, 480, 128);
  gtk_widget_set_size_request (_12, 40, 24);

  _13 = gtk_check_button_new_with_mnemonic (_("5"));
  gtk_widget_show (_13);
  gtk_fixed_put (GTK_FIXED (fixed8), _13, 408, 160);
  gtk_widget_set_size_request (_13, 40, 24);

  _14 = gtk_check_button_new_with_mnemonic (_("6"));
  gtk_widget_show (_14);
  gtk_fixed_put (GTK_FIXED (fixed8), _14, 480, 160);
  gtk_widget_set_size_request (_14, 40, 24);

  _15 = gtk_check_button_new_with_mnemonic (_("7"));
  gtk_widget_show (_15);
  gtk_fixed_put (GTK_FIXED (fixed8), _15, 408, 192);
  gtk_widget_set_size_request (_15, 40, 24);

  _16 = gtk_check_button_new_with_mnemonic (_("8"));
  gtk_widget_show (_16);
  gtk_fixed_put (GTK_FIXED (fixed8), _16, 480, 192);
  gtk_widget_set_size_request (_16, 40, 24);

  _17 = gtk_check_button_new_with_mnemonic (_("1"));
  gtk_widget_show (_17);
  gtk_fixed_put (GTK_FIXED (fixed8), _17, 656, 96);
  gtk_widget_set_size_request (_17, 40, 24);

  _18 = gtk_check_button_new_with_mnemonic (_("2"));
  gtk_widget_show (_18);
  gtk_fixed_put (GTK_FIXED (fixed8), _18, 732, 96);
  gtk_widget_set_size_request (_18, 40, 24);

  _19 = gtk_check_button_new_with_mnemonic (_("3"));
  gtk_widget_show (_19);
  gtk_fixed_put (GTK_FIXED (fixed8), _19, 656, 128);
  gtk_widget_set_size_request (_19, 40, 24);

  _20 = gtk_check_button_new_with_mnemonic (_("4"));
  gtk_widget_show (_20);
  gtk_fixed_put (GTK_FIXED (fixed8), _20, 732, 128);
  gtk_widget_set_size_request (_20, 40, 24);

  _21 = gtk_check_button_new_with_mnemonic (_("5"));
  gtk_widget_show (_21);
  gtk_fixed_put (GTK_FIXED (fixed8), _21, 656, 160);
  gtk_widget_set_size_request (_21, 40, 24);

  _22 = gtk_check_button_new_with_mnemonic (_("6"));
  gtk_widget_show (_22);
  gtk_fixed_put (GTK_FIXED (fixed8), _22, 732, 160);
  gtk_widget_set_size_request (_22, 40, 16);

  _23 = gtk_check_button_new_with_mnemonic (_("7"));
  gtk_widget_show (_23);
  gtk_fixed_put (GTK_FIXED (fixed8), _23, 656, 192);
  gtk_widget_set_size_request (_23, 40, 24);

  label56 = gtk_label_new (_("Duration"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed8), label56, 464, 328);
  gtk_widget_set_size_request (label56, 120, 48);

  book = gtk_button_new ();
  gtk_widget_show (book);
  gtk_fixed_put (GTK_FIXED (fixed8), book, 576, 480);
  gtk_widget_set_size_request (book, 104, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (book), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image12 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox10), image12, FALSE, FALSE, 0);

  label66 = gtk_label_new_with_mnemonic (_("book slot"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox10), label66, FALSE, FALSE, 0);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry1, 152, 24);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("North-parking-lot"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("East-parking-lot"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("West-parking-lot"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Sout-parking-lot"));

  _1 = gtk_check_button_new_with_mnemonic (_("1"));
  gtk_widget_show (_1);
  gtk_fixed_put (GTK_FIXED (fixed8), _1, 152, 96);
  gtk_widget_set_size_request (_1, 40, 24);

  _24 = gtk_check_button_new_with_mnemonic (_("8"));
  gtk_widget_show (_24);
  gtk_fixed_put (GTK_FIXED (fixed8), _24, 732, 192);
  gtk_widget_set_size_request (_24, 40, 24);

  label47 = gtk_label_new (_("Parking slot reservation "));
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label47);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed9);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview1, 16, 48);
  gtk_widget_set_size_request (treeview1, 744, 432);

  button2 = gtk_button_new_with_mnemonic (_("button2"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed9), button2, 584, 80);
  gtk_widget_set_size_request (button2, 68, 29);

  label57 = gtk_label_new (_("Reservation"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed9), label57, 16, 8);
  gtk_widget_set_size_request (label57, 128, 32);

  buttonrefrc = gtk_button_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (buttonrefrc);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonrefrc, 840, 176);
  gtk_widget_set_size_request (buttonrefrc, 104, 45);

  buttoncr = gtk_button_new_with_mnemonic (_("Cancle"));
  gtk_widget_show (buttoncr);
  gtk_fixed_put (GTK_FIXED (fixed9), buttoncr, 840, 288);
  gtk_widget_set_size_request (buttoncr, 104, 45);

  label48 = gtk_label_new (_("Reservation History "));
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label48);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed10);

  label58 = gtk_label_new (_("Working progressssssssssss"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed10), label58, 344, 184);
  gtk_widget_set_size_request (label58, 265, 167);

  label49 = gtk_label_new (_("New Deals "));
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label49);

  g_signal_connect ((gpointer) lougoutclient, "clicked",
                    G_CALLBACK (on_lougoutclient_clicked),
                    NULL);
  g_signal_connect ((gpointer) calendarclient, "day_selected_double_click",
                    G_CALLBACK (on_calendarclient_day_selected_double_click),
                    NULL);
  g_signal_connect ((gpointer) _2, "toggled",
                    G_CALLBACK (on_2_toggled),
                    NULL);
  g_signal_connect ((gpointer) _3, "toggled",
                    G_CALLBACK (on_3_toggled),
                    NULL);
  g_signal_connect ((gpointer) _4, "toggled",
                    G_CALLBACK (on_4_toggled),
                    NULL);
  g_signal_connect ((gpointer) _5, "toggled",
                    G_CALLBACK (on_5_toggled),
                    NULL);
  g_signal_connect ((gpointer) _6, "toggled",
                    G_CALLBACK (on_6_toggled),
                    NULL);
  g_signal_connect ((gpointer) _7, "toggled",
                    G_CALLBACK (on_7_toggled),
                    NULL);
  g_signal_connect ((gpointer) _8, "toggled",
                    G_CALLBACK (on_8_toggled),
                    NULL);
  g_signal_connect ((gpointer) _9, "toggled",
                    G_CALLBACK (on_9_toggled),
                    NULL);
  g_signal_connect ((gpointer) _10, "toggled",
                    G_CALLBACK (on_10_toggled),
                    NULL);
  g_signal_connect ((gpointer) _11, "toggled",
                    G_CALLBACK (on_11_toggled),
                    NULL);
  g_signal_connect ((gpointer) _12, "toggled",
                    G_CALLBACK (on_12_toggled),
                    NULL);
  g_signal_connect ((gpointer) _13, "toggled",
                    G_CALLBACK (on_13_toggled),
                    NULL);
  g_signal_connect ((gpointer) _14, "toggled",
                    G_CALLBACK (on_14_toggled),
                    NULL);
  g_signal_connect ((gpointer) _15, "toggled",
                    G_CALLBACK (on_15_toggled),
                    NULL);
  g_signal_connect ((gpointer) _16, "toggled",
                    G_CALLBACK (on_16_toggled),
                    NULL);
  g_signal_connect ((gpointer) _17, "toggled",
                    G_CALLBACK (on_17_toggled),
                    NULL);
  g_signal_connect ((gpointer) _18, "toggled",
                    G_CALLBACK (on_18_toggled),
                    NULL);
  g_signal_connect ((gpointer) _19, "toggled",
                    G_CALLBACK (on_19_toggled),
                    NULL);
  g_signal_connect ((gpointer) _20, "toggled",
                    G_CALLBACK (on_20_toggled),
                    NULL);
  g_signal_connect ((gpointer) _21, "toggled",
                    G_CALLBACK (on_21_toggled),
                    NULL);
  g_signal_connect ((gpointer) _22, "toggled",
                    G_CALLBACK (on_22_toggled),
                    NULL);
  g_signal_connect ((gpointer) _23, "toggled",
                    G_CALLBACK (on_23_toggled),
                    NULL);
  g_signal_connect ((gpointer) book, "clicked",
                    G_CALLBACK (on_book_clicked),
                    NULL);
  g_signal_connect ((gpointer) _1, "toggled",
                    G_CALLBACK (on_1_toggled),
                    NULL);
  g_signal_connect ((gpointer) _24, "toggled",
                    G_CALLBACK (on_24_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonrefrc, "clicked",
                    G_CALLBACK (on_buttonrefrc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttoncr, "clicked",
                    G_CALLBACK (on_buttoncr_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (client, client, "client");
  GLADE_HOOKUP_OBJECT (client, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (client, lougoutclient, "lougoutclient");
  GLADE_HOOKUP_OBJECT (client, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (client, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (client, image11, "image11");
  GLADE_HOOKUP_OBJECT (client, label59, "label59");
  GLADE_HOOKUP_OBJECT (client, ecid, "ecid");
  GLADE_HOOKUP_OBJECT (client, ecuser, "ecuser");
  GLADE_HOOKUP_OBJECT (client, label50, "label50");
  GLADE_HOOKUP_OBJECT (client, label65, "label65");
  GLADE_HOOKUP_OBJECT (client, label64, "label64");
  GLADE_HOOKUP_OBJECT (client, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (client, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (client, label51, "label51");
  GLADE_HOOKUP_OBJECT (client, label52, "label52");
  GLADE_HOOKUP_OBJECT (client, label53, "label53");
  GLADE_HOOKUP_OBJECT (client, label54, "label54");
  GLADE_HOOKUP_OBJECT (client, calendarclient, "calendarclient");
  GLADE_HOOKUP_OBJECT (client, entrydateclient, "entrydateclient");
  GLADE_HOOKUP_OBJECT (client, label55, "label55");
  GLADE_HOOKUP_OBJECT (client, spinbuttonduration, "spinbuttonduration");
  GLADE_HOOKUP_OBJECT (client, _2, "_2");
  GLADE_HOOKUP_OBJECT (client, _3, "_3");
  GLADE_HOOKUP_OBJECT (client, _4, "_4");
  GLADE_HOOKUP_OBJECT (client, _5, "_5");
  GLADE_HOOKUP_OBJECT (client, _6, "_6");
  GLADE_HOOKUP_OBJECT (client, _7, "_7");
  GLADE_HOOKUP_OBJECT (client, _8, "_8");
  GLADE_HOOKUP_OBJECT (client, _9, "_9");
  GLADE_HOOKUP_OBJECT (client, _10, "_10");
  GLADE_HOOKUP_OBJECT (client, _11, "_11");
  GLADE_HOOKUP_OBJECT (client, _12, "_12");
  GLADE_HOOKUP_OBJECT (client, _13, "_13");
  GLADE_HOOKUP_OBJECT (client, _14, "_14");
  GLADE_HOOKUP_OBJECT (client, _15, "_15");
  GLADE_HOOKUP_OBJECT (client, _16, "_16");
  GLADE_HOOKUP_OBJECT (client, _17, "_17");
  GLADE_HOOKUP_OBJECT (client, _18, "_18");
  GLADE_HOOKUP_OBJECT (client, _19, "_19");
  GLADE_HOOKUP_OBJECT (client, _20, "_20");
  GLADE_HOOKUP_OBJECT (client, _21, "_21");
  GLADE_HOOKUP_OBJECT (client, _22, "_22");
  GLADE_HOOKUP_OBJECT (client, _23, "_23");
  GLADE_HOOKUP_OBJECT (client, label56, "label56");
  GLADE_HOOKUP_OBJECT (client, book, "book");
  GLADE_HOOKUP_OBJECT (client, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (client, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (client, image12, "image12");
  GLADE_HOOKUP_OBJECT (client, label66, "label66");
  GLADE_HOOKUP_OBJECT (client, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (client, _1, "_1");
  GLADE_HOOKUP_OBJECT (client, _24, "_24");
  GLADE_HOOKUP_OBJECT (client, label47, "label47");
  GLADE_HOOKUP_OBJECT (client, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (client, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (client, button2, "button2");
  GLADE_HOOKUP_OBJECT (client, label57, "label57");
  GLADE_HOOKUP_OBJECT (client, buttonrefrc, "buttonrefrc");
  GLADE_HOOKUP_OBJECT (client, buttoncr, "buttoncr");
  GLADE_HOOKUP_OBJECT (client, label48, "label48");
  GLADE_HOOKUP_OBJECT (client, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (client, label58, "label58");
  GLADE_HOOKUP_OBJECT (client, label49, "label49");

  return client;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed11;
  GtkWidget *entryuserl;
  GtkWidget *entrypasswordl;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *button3;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (window1), fixed11);

  entryuserl = gtk_entry_new ();
  gtk_widget_show (entryuserl);
  gtk_fixed_put (GTK_FIXED (fixed11), entryuserl, 264, 80);
  gtk_widget_set_size_request (entryuserl, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryuserl), 8226);

  entrypasswordl = gtk_entry_new ();
  gtk_widget_show (entrypasswordl);
  gtk_fixed_put (GTK_FIXED (fixed11), entrypasswordl, 264, 136);
  gtk_widget_set_size_request (entrypasswordl, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypasswordl), 8226);

  label60 = gtk_label_new (_("USER "));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed11), label60, 72, 80);
  gtk_widget_set_size_request (label60, 88, 25);

  label61 = gtk_label_new (_("PASSWAORD"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed11), label61, 72, 136);
  gtk_widget_set_size_request (label61, 104, 33);

  label62 = gtk_label_new ("");
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed11), label62, 0, 0);
  gtk_widget_set_size_request (label62, 49, 17);

  label63 = gtk_label_new ("");
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed11), label63, 600, 280);
  gtk_widget_set_size_request (label63, 49, 17);

  button3 = gtk_button_new_with_mnemonic (_("LOG-IN"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed11), button3, 312, 224);
  gtk_widget_set_size_request (button3, 90, 48);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window1, entryuserl, "entryuserl");
  GLADE_HOOKUP_OBJECT (window1, entrypasswordl, "entrypasswordl");
  GLADE_HOOKUP_OBJECT (window1, label60, "label60");
  GLADE_HOOKUP_OBJECT (window1, label61, "label61");
  GLADE_HOOKUP_OBJECT (window1, label62, "label62");
  GLADE_HOOKUP_OBJECT (window1, label63, "label63");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");

  return window1;
}

