/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_espace_admin (void);
GtkWidget* create_Add_agent (void);
GtkWidget* create_mod_agent (void);
GtkWidget* create_client (void);
GtkWidget* create_window1 (void);
